### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by stevenhalase** [smartcontractkit/hello_chainlink#7]
I'm running into things and I maybe just need clarification:

Uptime_SLA Example
- Files renamed? to http_json_x10000_job.json but create_http_json_x10000_job references ./x100_job.json?
- Migration imports not working?

Echo_Server
- SSH identifier
resolved "git+ssh://git@github.com/smartcontractkit/chainlink.git#acd38137325c250fc90f2ddadb1f1f43e38e53e3"

**Comment by se3000** [comment]
Thanks for bringing this to our attention. We resolved both of these issues in: https://github.com/smartcontractkit/hello_chainlink/pull/8

You should also pull down the latest version of ChainLink before running this. I'm going to close this issue, but feel free to reopen it if you run into other problems.
